home:
  alias: 'expose-framework/get-started'

pages:
  theme: nimble
  markdown_extra: false
  process:
    markdown: true
    twig: false

cache:
  enabled: false
  check:
    pages: true
  driver: auto
  prefix: 'g'

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: false
  css_minify: true
  css_rewrite: true
  js_pipeline: false
  js_minify: true

debugger:
  enabled: true
  strict: false
  max_depth: 10
  log:
    enabled: false
    timing: false
